### ISSUE TITLE
Question on Gpu Glyph Compiler

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [littlektframework/littlekt#90]
I found out your implementation of [Gpu Glyph Compiler](https://github.com/littlektframework/littlekt/blob/master/core/src/commonMain/kotlin/com/lehaine/littlekt/graphics/font/internal/GpuGlyphCompiler.kt) very interesting. What king of algorithm did you use here? Is it your kind of personal approach?

**Comment by LeHaine** [comment]
The algorithm I used for the GPU glyph font and compiler are not mine. The algorithm is from **Will Dobbie's** [GPU text rendering](https://wdobbie.com/post/gpu-text-rendering-with-vector-textures/) article which goes into detail on how it works. Another good code resource based off of Will's algorithm is [GlLabel](https://github.com/azsn/gllabel).

**Comment by LeHaine** [comment]
2D was the primary goal of the framework, mainly because that is all I used for my personal games. But I have been thinking adding 3D support and such as more of a long term thing after 2D is tightened up quit a bit. It is definitely a possibility. 

Also feel free to use the discussions [Q&A](https://github.com/littlektframework/littlekt/discussions/categories/q-a) for any other questions and such and I will gladly answer!
